version: "3.8"

services:
  ergo:
    image: ghcr.io/ergochat/ergo:stable
    ports:
      - "6697:6697/tcp"
    volumes:
      - ergodata:/ircd
      - ./ircd.yaml:/ircd/ircd.yaml:ro
      - /etc/letsencrypt/live/irc.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/irc.terminaldweller.com/fullchain.pem
      - /etc/letsencrypt/live/irc.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/irc.terminaldweller.com/privkey.pem
    networks:
      - ergonet
    labels:
      - traefik.enable=false
volumes:
  ergodata:
networks:
  ergonet:
  traefiknet:
    name: matrix_default
    external: true
