version: "3"
services:
  nginx:
    image: nginx:stable
    networks:
      - mainnet
    ports:
      - "7773:8080"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/terminaldweller.com/:/certs/
      - ./srv:/srv
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
networks:
  mainnet:
