version: "3"
services:
  cgit:
    image: woahbase/alpine-cgit:x86_64
    networks:
      - cgitnet
    ports:
      - "8041:80"
      - "8042:22"
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
    volumes:
      # - ./cgit/cgitrc:/etc/cgitrc:ro
      - storage:/home/git/repositories
      - ./data/ssh:/etc/ssh
      # - ./data/web:/var/www
      # - /etc/hosts:/etc/hosts:ro
      # - /etc/localtime:/etc/localtime:ro
      # - ./cgit.conf:/etc/lighttpd/conf.d/cgit.conf
  bootstrap:
    image: bootstrap
    build:
      context: ./bootstrap
    networks:
      - bootstrapnet
    volumes:
      - storage:/etc/gitrepos/
    entrypoint: ["/docker-entrypoint.sh"]
    cap_drop:
      - ALL
networks:
  cgitnet:
  bootstrapnet:
volumes:
  storage:
