version: "3"
services:
  cgit:
    image: cgit
    build:
      context: ./cgit/
    networks:
      - cgitnet
    ports:
      - "127.0.0.1:8041:80"
      - "8042:22"
      - "8043:443"
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - PYGMENTIZE_STYLE=paraiso-dark
    volumes:
      - ./cgit/cgitrc:/etc/cgitrc:ro
      - storage:/home/git/repositories
      - ./data/ssh:/etc/ssh
      # - ./data/web:/var/www
      # - /etc/hosts:/etc/hosts:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./cgit.conf:/etc/lighttpd/cgit.conf:ro
      - /etc/letsencrypt/live/git.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/git.terminaldweller.com/fullchain.pem:ro
      - /etc/letsencrypt/live/git.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/git.terminaldweller.com/privkey.pem:ro
      - cache:/cgit_cache
      - ./authorized_keys:/home/git/.ssh/authorized_keys
  bootstrap:
    image: bootstrap
    build:
      context: ./bootstrap
    networks:
      - bootstrapnet
    volumes:
      - storage:/etc/gitrepos/
    entrypoint: ["/docker-entrypoint.sh"]
      # cap_drop:
      # - ALL
      # healthcheck:
      # test: exit 1
      # interval: 1d
      # timeout: 10s
      # retries: 1
    restart: unless-stopped
networks:
  cgitnet:
  bootstrapnet:
volumes:
  storage:
  cache:
