#!/usr/bin/env python3
# _*_ coding=utf-8 _*_

import re


def main():
    with open("/home/devi/.irssi/config", "r") as config_file:
        lines = config_file.readlines()
        for line in lines:
            print(re.sub("password\\s*=\\s*\"(.*)\"",
                         "password=\"\"", line), end="")


if __name__ == "__main__":
    main()
