[color]
header_fg = 4
header_bg = 0
active_fg = 23
active_bg = 0
disabled_fg = 8
disabled_bg = 0
timeout_fg = 63
timeout_bg = 0
unknown_fg = 38
unknown_bg = 0
down_fg = 208
down_bg = 0
box_fg = 22
box_bg = 0

[tunnel.socks5ir]
address = "127.0.0.1"
port = 9997
command = "autossh -M 0 -N -D 9997 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 1022 87.236.209.206"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9997 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks_can]
address = "127.0.0.1"
port = 9999
command = "autossh -M 0 -N -D 9999 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l rooot -p 1022 192.99.102.52"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9999 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = false

[tunnel.socks5_3]
address = "0.0.0.0"
port = 9995
command = "autossh -M 0 -N -D 0.0.0.0:9995 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o VerifyHostKeyDNS=no -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l root -p 2022 185.112.147.110"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9995 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks5_5]
address = "0.0.0.0"
port = 9990
command = "autossh -M 0 -N -D 0.0.0.0:9990 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9990 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks5_v]
address = "0.0.0.0"
port = 9985
command = "autossh -M 0 -N -D 0.0.0.0:9985 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.244.29.79"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9985 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks5_8]
address = "0.0.0.0"
port = 9989
command = "autossh -M 0 -N -D 0.0.0.0:9989 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9989 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks5_10]
address = "0.0.0.0"
port = 9984
command = "autossh -M 0 -N -D 0.0.0.0:9984 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 89.147.110.30"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9984 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.socks5_j]
address = "0.0.0.0"
port = 9969
command = "autossh -M 0 -N -D 0.0.0.0:9969 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.46.113"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9969 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.i2pmapped6http]
address = "0.0.0.0"
port = 9064
command = "autossh -M 0 -N -L 0.0.0.0:9064:127.0.0.1:4444 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --proxy http://127.0.0.1:9064 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped6server]
address = "0.0.0.0"
port = 9066
command = "autossh -M 0 -N -L 0.0.0.0:9066:127.0.0.1:7070 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 localhost:9066'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped6socks]
address = "0.0.0.0"
port = 9067
command = "autossh -M 0 -N -L 0.0.0.0:9067:127.0.0.1:4447 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --socks5 socks5h://127.0.0.1:9067 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped6irssilitia]
address = "0.0.0.0"
port = 9068
command = "autossh -M 0 -N -L 0.0.0.0:9068:127.0.0.1:6668 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = ""
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped6irssipostman]
address = "0.0.0.0"
port = 9069
command = "autossh -M 0 -N -L 0.0.0.0:9069:127.0.0.1:6669 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = ""
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped6irssinerds]
address = "0.0.0.0"
port = 9070
command = "autossh -M 0 -N -L 0.0.0.0:9070:127.0.0.1:6670 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = ""
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped8http]
address = "0.0.0.0"
port = 9164
command = "autossh -M 0 -N -L 0.0.0.0:9164:127.0.0.1:4444 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --proxy http://127.0.0.1:9164 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped8server]
address = "0.0.0.0"
port = 9166
command = "autossh -M 0 -N -L 0.0.0.0:9166:127.0.0.1:7070 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 localhost:9166'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmapped8socks]
address = "0.0.0.0"
port = 9167
command = "autossh -M 0 -N -L 0.0.0.0:9167:127.0.0.1:4447 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --socks5 socks5h://127.0.0.1:9167 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmappedvhttp]
address = "0.0.0.0"
port = 9264
command = "autossh -M 0 -N -L 0.0.0.0:9264:127.0.0.1:4444 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.244.29.79"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --proxy http://127.0.0.1:9264 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmappedvserver]
address = "0.0.0.0"
port = 9266
command = "autossh -M 0 -N -L 0.0.0.0:9266:127.0.0.1:7070 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.244.29.79"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 localhost:9266'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmappedvsocks]
address = "0.0.0.0"
port = 9267
command = "autossh -M 0 -N -L 0.0.0.0:9267:127.0.0.1:4447 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.244.29.79"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 --socks5 socks5h://127.0.0.1:9267 http://iedzwh5v2vouywqy4eak3eu33amfn3rzhdcln7j4r5kcyvf46cea.b32.i2p:7774/'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.i2pmappedjserver]
address = "0.0.0.0"
port = 9366
command = "autossh -M 0 -N -L 0.0.0.0:9366:127.0.0.1:7070 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.46.113"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I -4 localhost:9366'
test_command_result = "200"
test_interval = 300
test_timeout = 30
auto_start = true

[tunnel.tormapped6]
address = "127.0.0.1"
port = 9053
command = "autossh -M 0 -N -L 9053:127.0.0.1:9050 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9053 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = true

[tunnel.tormapped6control]
address = "0.0.0.0"
port = 8053
command = "autossh -M 0 -N -L 0.0.0.0:8053:127.0.0.1:9051 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = ''
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = false

[tunnel.tormapped8]
address = "0.0.0.0"
port = 9054
command = "autossh -M 0 -N -L 0.0.0.0:9054:127.0.0.1:9050 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9054 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = true

[tunnel.tormapped8control]
address = "0.0.0.0"
port = 8054
command = "autossh -M 0 -N -L 0.0.0.0:8054:127.0.0.1:9051 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = ''
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = false

[tunnel.tormappedv]
address = "0.0.0.0"
port = 9055
command = "autossh -M 0 -N -L 0.0.0.0:9055:127.0.0.1:9050 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.244.29.79"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9055 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = true

[tunnel.tormappedj]
address = "0.0.0.0"
port = 9056
command = "autossh -M 0 -N -L 0.0.0.0:9056:127.0.0.1:9050 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.46.113"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -4 --socks5 socks5h://127.0.0.1:9056 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = true

[tunnel.bnc_tor_g]
address = "0.0.0.0"
port = 9788
command = "autossh -M 0 -N -L 0.0.0.0:9788:127.0.0.1:1026 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l root -p 3333 65.109.235.54"
test_command = ''
test_command_result = "200"
test_interval = 300
test_timeout = 20
auto_start = true

[tunnel.haproxy_prom_mapped]
address = "0.0.0.0"
port = 9099
command = "autossh -M 0 -N -L 0.0.0.0:9099:127.0.0.1:9099 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 1022 87.236.209.206"
test_command = "curl -s localhost:9099"
test_command_result = "<a href=\"/graph\">Found</a>."
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.slackircd]
address = "0.0.0.0"
port = 7997
command = "autossh -M 0 -N -L 0.0.0.0:7997:127.0.0.1:6697 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l rooot -p 1022 192.99.102.52"
test_command = ""
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = false

[tunnel.ircgitter]
address = "0.0.0.0"
port = 5667
command = "autossh -M 0 -N -L 0.0.0.0:5667:127.0.0.1:5667 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.47.208"
test_command = ""
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = false

[tunnel.upnp_2234]
address = "127.0.0.1"
port = 2235
command = "autossh -M 0 -N -L 127.0.0.1:2235:*:2234 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 185.130.45.46"
test_command = ""
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = false

[tunnel.6socks5_6]
address = "::1"
port = 8990
command = "autossh -M 0 -N -D [::1]:8990 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e01:3:204::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8990 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.6socks5_7]
address = "::1"
port = 8997
command = "autossh -M 0 -N -D [::1]:8997 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e03:3:26::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8997 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.6socks5_8]
address = "::1"
port = 8989
command = "autossh -M 0 -N -D [::1]:8989 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e03:3:bd::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8989 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.6socks5_9]
address = "::1"
port = 8988
command = "autossh -M 0 -N -D 8988 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e01:3:1c4::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8988 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.6socks5_vv]
address = "::1"
port = 8987
command = "autossh -M 0 -N -D 8987 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e01:3:30c::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8987 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.6socks5_j]
address = "::1"
port = 8967
command = "autossh -M 0 -N -D 8967 -o ServerAliveInterval=180 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -l ubuntu -p 3333 2a07:e01:3:2eb::1"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -k -I -6 --socks5 socks5h://[::1]:8967 https://icanhazallips.terminaldweller.com:9380'
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.lxc_geth]
address = "0.0.0.0"
port = 8545
command = "autossh -M 0 -N -L 0.0.0.0:8545:127.0.0.1:8545 -l ubuntu 10.167.131.186"
test_command = ''
test_command_result = "200"
test_interval = 300
test_timeout = 10
auto_start = false

[tunnel.netdata_3]
address = "127.0.0.1"
port = 7003
command = "autossh -M 0 -N -L 127.0.0.1:7003:127.0.0.1:19999 -l root -p 2022 185.112.147.110"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I 127.0.0.1:7003'
test_command_result = "400"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.netdata_6]
address = "127.0.0.1"
port = 7006
command = "autossh -M 0 -N -L 127.0.0.1:7006:127.0.0.1:19999 -l ubuntu -p 3333 185.130.45.46"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I 127.0.0.1:7006'
test_command_result = "400"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.netdata_8]
address = "127.0.0.1"
port = 7008
command = "autossh -M 0 -N -L 127.0.0.1:7008:127.0.0.1:19999 -l ubuntu -p 3333 185.130.47.208"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I 127.0.0.1:7008'
test_command_result = "400"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.netdata_10]
address = "127.0.0.1"
port = 7010
command = "autossh -M 0 -N -L 127.0.0.1:7010:127.0.0.1:19999 -l root -p 3333 89.147.110.30"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I 127.0.0.1:7010'
test_command_result = "400"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.netdata_j]
address = "127.0.0.1"
port = 7011
command = "autossh -M 0 -N -L 127.0.0.1:7011:127.0.0.1:19999 -l ubuntu -p 3333 185.130.46.113"
test_command = 'curl -s -o /dev/null -s -w "%{http_code}" -I 127.0.0.1:7011'
test_command_result = "400"
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.generic_v4_l_6]
address = "127.0.0.1"
port = 6006
command = "autossh -M 0 -N -L 127.0.0.1:6006:127.0.0.1:6006 -l ubuntu -p 3333 185.130.45.46"
test_command = ''
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.generic_v4_l_8]
address = "127.0.0.1"
port = 6008
command = "autossh -M 0 -N -L 127.0.0.1:6008:127.0.0.1:6006 -l ubuntu -p 3333 185.130.47.208"
test_command = ''
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.generic_v4_l_10]
address = "127.0.0.1"
port = 6010
command = "autossh -M 0 -N -L 127.0.0.1:6010:127.0.0.1:6006 -l ubuntu -p 3333 89.147.110.30"
test_command = ''
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.generic_v4_l_j]
address = "127.0.0.1"
port = 6011
command = "autossh -M 0 -N -L 127.0.0.1:6011:127.0.0.1:6006 -l ubuntu -p 3333 185.130.46.113"
test_command = ''
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = true

[tunnel.lxc_python_lsp_jedi]
address = "127.0.0.1"
port = 4401
command = "autossh -M 0 -N -L 127.0.0.1:4401:127.0.0.1:4401 -l ubuntu 10.167.131.24"
test_command = ''
test_command_result = ""
test_interval = 300
test_timeout = 10
auto_start = false
