version: "3"
services:
  nginx:
    image: nginx
    build:
      context: .
    networks:
      - cargonet
    ports:
      - "7777:8080"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/cargo:/cargo
      - /etc/letsencrypt/live/cargo.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/cargo.terminaldweller.com/fullchain.pem:ro
      - /etc/letsencrypt/live/cargo.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/cargo.terminaldweller.com/privkey.pem:ro
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
networks:
  cargonet:
