version: "3"
services:
  nginx:
    image: nginx:stable
    networks:
      - mainnet
    ports:
      - "172.16.0.1:80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./srv:/srv:ro
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
networks:
  mainnet:
