version: "3.4"
services:
  postgres:
    image: postgres:alpine3.14
    ports:
      "127.0.0.1:5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/prosody
    networks:
      - xmppnet
    cap_drop:
      - ALL
  prosody:
    image: prosody/prosody:0.11.9
    restart: unless-stopped
    ports:
      - "5080:80/tcp"
      - "5222:5222/tcp"
      - "5280:5280/tcp"
      - "5281:5281/tcp"
      - "5347:5347/tcp"
      - "5582:5582/tcp"
    volumes:
      - ./config/prosody.cfg.lua:/etc/prosody:ro
      - ./log:/var/log/prosody
      - ./modules:/usr/lib/prosody-modules
    environment:
      - LOCAL=chat
      - DOMAIN=terminaldweller.com
      - PASSWORD=letstryxmpp
    networks:
      - xmppnet
    cap_add:
    cap_drop:
      - ALL
networks:
  xmppnet:
    driver: bridge
volumes:
  postgresdata:
