version: "3"
services:
  rssbridge:
    image: rssbridge/rss-bridge:latest
    networks:
      - rssbridgenet
    ports:
      - "3000:80"
    restart: unless-stopped
    # volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - /home/ubuntu/cargo:/cargo
    # cap_drop:
    #   - ALL
networks:
  rssbridgenet:
