version: "3"
services:
  dnsproxy:
    image: bloodstalker/dnsproxy
    # build:
    #   context: .
    networks:
      - doh2net
    ports:
      - "8844:8844"
      - "8845:8845"
      - "8846:8846"
      - "8847:8847"
    restart: unless-stopped
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - /etc/letsencrypt/archive/doh2.terminaldweller.com/:/certs/:ro
networks:
  doh2net:
