version: '3'
services:
  app:
    image: thelounge/thelounge:4.4.1
    volumes:
      - thelounge-data:/var/opt/thelounge
    networks:
      - loungenet
    labels:
      - traefik.enable=true
        #- traefik.docker.network=traefik-public
        #- traefik.constraint-label=traefik-public
        #- traefik.http.routers.thelounge-http.rule=Host(`lounge.terminaldweller.com`)
        #- traefik.http.routers.thelounge-http.entrypoints=http
        #- traefik.http.routers.thelounge-http.entrypoints=websecure
        #- traefik.http.routers.thelounge-http.middlewares=https-redirect
      - traefik.http.routers.thelounge.rule=Host(`lounge.terminaldweller.com`)
      - traefik.http.routers.thelounge.entrypoints=websecure
      - traefik.http.routers.thelounge.tls=true
      - traefik.http.routers.thelounge.tls.certresolver=letls
        #- traefik.http.services.thelounge.loadbalancer.server.port=9000
networks:
  loungenet:
    name: matrix_default
    external: true
volumes:
  thelounge-data:
