version: "3"
services:
  browsh:
    image: browsh/browsh:v1.8.0
    networks:
      - browshnet
    ports:
      - "127.0.0.1:2333:4333"
    restart: unless-stopped
    entrypoint: "/app/bin/browsh"
    command: ["--http-server-mode"]
    depends_on:
      - nginx
  nginx:
    image: nginx:stable
    ports:
      - "4333:443"
    networks:
      - browshnet
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/browsh.terminaldweller.com/:/certs/:ro
networks:
  browshnet:
