version: "3.8"
services:
  bitlbee:
    image: ezkrg_bitlbee_libpurple
    networks:
      - bitlbeenet
    ports:
      - "8667:6667"
    # user: 1000:1000
    restart: unless-stopped
    user: "bitlbee:bitlbee"
    command: ["/usr/sbin/bitlbee", "-F","-n","-u","bitlbee","-c","/var/lib/bitlbee/bitlbee.conf", "-d","/var/lib/bitlbee"]
    volumes:
      - ./conf/bitlbee.conf:/var/lib/bitlbee/bitlbee.conf
      - userdata:/var/lib/bitlbee
      - /home/devi/.cache/docker-bitlbee/signald/run:/var/run/signald
  # signald:
  #   image: signald/signald
  #   networks: 
  #     - signalnet
  #   restart: unless-stopped
  #   volumes:
  #     - /home/devi/.cache/docker-bitlbee/signald/run:/signald
  #     - ./net.properties:/conf/net.properties:ro
  #   environment:
  #     - ALL_PROXY=http://192.168.1.214:8118
  #     - FTP_PROXY=http://192.168.1.214:8118
  #     - HTTP_PROXY=http://192.168.1.214:8118
  #     - HTTPS_PROXY=http://192.168.1.214:8118
  #     - NOPROXY=localhost,127.0.0.0/8,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
  # matterircd:
  #   image: 42wim/matterircd:0.26
  #   networks:
  #     - matterircdnet
  #   ports:
  #     - "8668:6667"
  #   restart: unless-stopped
  #   environment:
  #     - ALL_PROXY=socks5h://192.168.1.214:9995
  #     - FTP_PROXY=http://192.168.1.214:8118
  #     - HTTP_PROXY=http://192.168.1.214:8118
  #     - HTTPS_PROXY=http://192.168.1.214:8118
  #     - NOPROXY=localhost,127.0.0.0/8,172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
  #   command: ["--conf", "/matterircd.conf"]
  #   volumes:
  #     - ./matterircd.toml:/matterircd.toml:ro
networks:
  bitlbeenet:
  signalnet:
  matterircdnet:
volumes:
  userdata:
