version: "3.7"
services:
  bitlbee:
    image: bitlbee_devi
    networks:
      - bitlbeenet
    ports:
      - "8667:6667"
    restart: unless-stopped
    network_mode: bridge
    user: "bitlbee:bitlbee"
    command: ["/usr/sbin/bitlbee", "-F","-n","-u","bitlbee","-c","/var/lib/bitlbee/bitlbee.conf", "-d","bitlbee-user-data"]
    volumes:
      - ./conf/bitlbee.conf:/var/lib/bitlbee/bitlbee.conf
networks:
  bitlbeenet:
    ipam:
      driver: overlay
      config:
        - subnet: 172.18.0.0/16
        - ip_range: 172.18.5.0.24
        - gateway: 172.18.0.1
