version: "3.7"
services:
  bitlbee:
    image: ezkrg_bitlbee_libpurple
    networks:
      - bitlbeenet
    ports:
      - "8667:6667"
    user: 1000:1000
    restart: unless-stopped
    user: "bitlbee:bitlbee"
    command: ["/usr/sbin/bitlbee", "-F","-n","-u","bitlbee","-c","/var/lib/bitlbee/bitlbee.conf", "-d","/var/lib/bitlbee"]
    volumes:
      - ./conf/bitlbee.conf:/var/lib/bitlbee/bitlbee.conf
      - userdata:/var/lib/bitlbee
networks:
  bitlbeenet:
volumes:
  userdata:
