#!/usr/bin/env sh
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.246"

# open settings options
tmux send-keys "$W3M_HOTKEY_OPTIONS"
# jump to user agent
tmux send-keys "155$W3M_HOTKEY_LINK_BEGIN"
# clear user agent string
tmux send-keys 'Enter' 'C-u'
# new user agent string
tmux send-keys "$USER_AGENT" 'Enter'
# save changes
tmux send-keys "173$W3M_HOTKEY_LINK_BEGIN" 'Enter'
# refresh page
tmux send-keys "$W3M_HOTKEY_RELOAD"
