version: "3.4" 
services:
  ejabberd:
    image: ejabberd/ecs:21.07
    networks:
      - ejabberdnet
    ports:
      - "5222:5222"
      - "127.0.0.1:5269:5269"
      - "5280:5280"
      - "127.0.0.1:5443:5443"
      - "127.0.0.1:1883:1883"
      - "5080:5080"
    restart: unless-stopped
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
networks:
  ejabberdnet:
