version: "3.4" 
services:
  ejabberd:
    image: ejabberd/ecs:21.07
    networks:
      - ejabberdnet
    ports:
      - "80:80"
      - "5222:5222"
      - "127.0.0.1:5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:5080:5080"
    restart: unless-stopped
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml
      - ./acme:/var/lib/ejabberd/acme
      - ./dh:/usr/local/etc/ejabberd
networks:
  ejabberdnet:
# openssl dhparam -out dhparams.pem 4096
# sudo certbot certonly --standalone --email devi@terminaldweller.com --non-interactive --agree-tos -d chat.terminaldweller.com --preferred-challenges http
