apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: linuxserver/ipfs:2.13.0
        ports:
        - containerPort: 4001
        - containerPort: 5001
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
spec:
  selector:
    app: ipfs
  type: NodePort
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
      nodePort: 30401
      name: "ipfs-tcp-4001"
    - protocol: UDP
      port: 4001
      targetPort: 4001
      nodePort: 30401
      name: "ipfs-udp-4001"
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30402
      name: "ipfs-tcp-80"
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30403
      name: "ipfs-tcp-443"
