apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    app: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: klutchell/unbound
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-service
spec:
  selector:
    app: unbound
  type: NodePort
  ports:
    - protocol: UDP
      port: 53
      name: "unbound-udp-53"
      targetPort: 53
      nodePort: 30853
    - protocol: TCP
      port: 53
      name: "unbound-tcp-53"
      targetPort: 53
      nodePort: 30853
