apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  lables:
    app: unbound
spec:
  replicas: 1
  selctor:
    matchlabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - name: unbound
        image: klutchell/unbound
        ports:
        - containerPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: unbound-service
spec:
  selector:
    app: unbound
  type: LoadBalancer
  ports:
    - protocol: UDP
      port: 53
      targetPort: 53
      nodePort: 53
