apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: bitlbee-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
