version: "3"
services:
  nginx:
    image: nginx:stable
    networks:
      - mainnet
    ports:
      - "[21e:cd57:a147:322a:723b:a322:e4c8:c26e]:80:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./srv:/srv:ro
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
networks:
  mainnet:
